### PR TITLE
Add completion

### PR DESCRIPTION
**Pull request by Carpetsmoker**
2017-11-30-011735_510x201_scrot

Is this something you'd be interested in adding?

This is a very quick implementation mostly copied from another plugin I made a few years ago, and doesn't *quite* work right; but it does show how the code would basically look like. I can finish it up if you'd like to add it.

Use `<C-x><C-t>` to start the completion.

### CODE REVIEW

**Comment by joereynolds** [comment]
There is a deoplete source already made here

https://github.com/joereynolds/deoplete-minisnip

Though maybe native completion would be better if it "just worked"

**Comment by Carpetsmoker** [comment]
> There is a deoplete source already made here

Using Deoplete is more than a little overkill for such a small feature for such a small plugin :-)

Anyway, I'll finish this PR up later then :+1:

**Comment by Carpetsmoker** [comment]
Alright; I finished it up. I changed the mapping to `<C-x><C-t>`, because `<C-m>` is the same as `<CR>`, which makes mapping both the enter key and `<C-m>`  impossible (gotta love terminals...)

**Comment by joereynolds** [comment]
I'll look at testing this some time today. This means one less plugin for me to include (deoplete-minisnip), good work!

**Comment by Carpetsmoker** [comment]
Interesting; it works for me.

**Comment by Carpetsmoker** [comment]
Okay, I pushed an update which *may* fix it, but I wasn't able to reproduce that error.

Another thing that I should fix is that it should show `pattern not found` when there are no completions. An `echo` or `echom` get overriden, and won't be seen, So need to look in how to do that.

**Comment by joereynolds** [comment]
Cool, that fixes the error message problem. I've managed to get a gif of me reproducing the completion bug with a minimal vimrc.

Notice that a strap `p` gets inserted when I press `<tab>`

completion-minisnip

**Comment by joereynolds** [comment]
Works a treat!

One small thing (sorry) can we add this to the docs?

**Comment by Carpetsmoker** [comment]
The "p" is just some temporary  output; it doesn't actually get inserted in the buffer. I noticed that too, but I just assumed it was a generic problem due to terminal escape code whatnot, but it seems this problem isn't present on master :-/ I changed the mapping from `<Plug>Name` to `<Plug>(name)`,  which seems to fix it for reasons I don't quite understand. Using `(name)` is more standard anyway, AFAIK. This also seems to fix things in the bottom-right? Not sure why that happened, either :-/

**Comment by joereynolds** [comment]
Works a treat!

**Comment by Carpetsmoker** [comment]
> One small thing (sorry) can we add this to the docs?

I already added an entry for the mapping: https://github.com/joereynolds/vim-minisnip/pull/6/files#diff-e6ab5d74568837d50ee63e2c0c00b05fR42

Was there some other doc you would want to see?

BTW, I also want to fix the error when there are no matches; otherwise it's very confusing imho. I'll do that this evening.

**Comment by joereynolds** [comment]
Hey @Carpetsmoker 
 
No other docs are needed (I think), great work on the prs so far! :D

**Pull request merged**
