### PR TITLE
Add ftdetect

### PR DESCRIPTION
**Pull request by Carpetsmoker**
Fixes #3

### CODE REVIEW

**Comment by joereynolds** [comment]
Looks good, can we leave the syntax doc in though? Or at least clarify somewhere that synax highlighting is available if your filetype is `minisnip`?

**Comment by Carpetsmoker** [comment]
It's mentioned in the `minisnip_dir` docs; I thought that was enough? Could maybe add a `ft-minisnip` tag to that or something.

**Comment by joereynolds** [comment]
It mentions it there but there's no mention of the fact that it comes with syntax highlighting, you'd have to read the source code to find that out :(

**Comment by joereynolds** [comment]
Thanks!

**Pull request merged**
