### PR TITLE
Add support for final placeholders

### PR DESCRIPTION
**Pull request by thepith**
Final placeholders are one, which are to be selected last. This way one
can easily select the final cursor position, even if it is in the middle
of the snippet.

* The default delimiters for final placeholders are `{{-` and `-}}`
* Added documentation
* Added unit tests

### CODE REVIEW

**Comment by joereynolds** [comment]
Hey @thepith,

Looks good though I don't really see it being used that often if I'm honest.
I'd like to try and keep minisnip 'mini' as in, few features but they work as expected.

What are your use cases for this out of curiosity?
(Sorry for the late reply)

**Comment by thepith** [comment]
Hi,

the application is all snippets in which one wants to sourround the cursor with a snippet. Consider an include guard:
```
#ifndef {{+~toupper(expand('%:r').'_H')+}}
 #define {{+~toupper(expand('%:r').'_H')+}}
{{--}}
#endif /* {{+~toupper(expand('%:r').'_H')+}} */
```
I use it for `fortran` modules/functions/submodules:
```
module {{+MODULE_NAME+}}
   {{--}}
end module {{+~\~1+}}
```
or a `latex` snippet:
```
\begin{{{++}}}
   {{--}}
\end{{{+~\~1+}}}
```
I agree that it is probabbly not the most widely used feature, but with grep I found around 70 snippets in the [vim-snippets reo](https://github.com/honza/vim-snippets), which would utilize such a feature.

**Comment by sigzero** [comment]
Just as a comment. Almost every editor that I have used that has a snippet plugin utilizes some form of final placeholder. Most of the snippet plugins in Vim do, jEdit uses $end, Notepad++ uses $[0[]0] and so forth. I just use an empty minisnip since it serves the same purpose.

**Comment by joereynolds** [comment]
Well, if you're all in favour I'll merge it in soon :)

**Pull request merged**
