### PR TITLE
[WIP] Correctly insert snippet at cursor position

### LINKED ISSUE #10: Insert snippet at cursor location rather than at end of line
Is it possible to insert the snippet at the cursor location? I'm mostly using minisnip for LaTex and it's frustrating when I attempt to evaluate a snippet in the middle of a line only to have it insert at the end of the line.

I was thinking instead of appending after the line and joining them, we could put it in an expression register and then paste it. It could look something like this:
`silent! execute "normal \"=\"".join(lns, '\n')."\"\<C-M>P"`

There might be cleaner solutions though.

### PR DESCRIPTION
**Pull request by Carpetsmoker**
Fixes #10

May need some more work/testing; it's a bit of a quick patch, but seems
to work well in a quick test.

### CODE REVIEW

**Comment by joereynolds** [comment]
Hey @Carpetsmoker I'll try and take a look at this some time this week. Cheers!

**Comment by Carpetsmoker** [comment]
No hurries!

**Comment by joereynolds** [comment]
Hey @Carpetsmoker 

This seems to have screwed with the indentation when a snippet is expanded

#### Before
```
    private function myTestFunction()
    {
        foreach ($ as ${{++}}) {
            {{++}}
        }
        $a = 5;
        $b = 6;


        $c = $a + $b;
    }

```
#### After

```
    private function myTestFunction()
    {
                foreach ($ as ${{++}}) {
            {{++}}
        }


        $c = $a + $b;
    }
```

Not mandatory but some tests to show that is fixed and to stop regressing would be great!

**Comment by Carpetsmoker** [comment]
Yeah, noticed that as well. I'll take a look next week. Like I said, this was just a quick patch.

**Pull request closed without merging**
